[project]
name = "llm-human-replica"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "loguru>=0.7.3",
    "pydantic-settings>=2.8.1",
    "pymongo>=4.11.3",
    "zenml>=0.80.1",
]
